packaging_format = 2

id = "ipfs-cluster"
name = "ipfs-cluster"
description.en = "Explain in *a few (10~15) words* the purpose of the app or what it actually does (it is meant to give a rough idea to users browsing a catalog of 100+ apps)"
description.fr = "Expliquez en *quelques* (10~15) mots l'utilité de l'app ou ce qu'elle fait (l'objectif est de donner une idée grossière pour des utilisateurs qui naviguent dans un catalogue de 100+ apps)"

version = "1.0.6~ynh1"

maintainers = [""]

[upstream]
license = "MIT"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://github.com/ipfs-cluster/ipfs-cluster/blob/v1.0.6/README.md"
userdoc = "https://ipfscluster.io/documentation/"
code = "https://some.forge.com/example/example"

[integration]
yunohost = ">= 11.1.19"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://dist.ipfs.tech/ipfs-cluster-service/v1.0.6/ipfs-cluster-service_v1.0.6_linux-amd64.tar.gz"
        sha256 = "79f4caadb5437f3e3c064d03fc88a4db26c81f484560caa101ed9300f30d5732"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
